site_name: M365 Toolkit
site_url: https://emildosen.github.io/m365-toolkit/
repo_url: https://github.com/emildosen/m365-toolkit
repo_name: emildosen/m365-toolkit

theme:
  name: material
  features:
    - navigation.sections
    - navigation.path
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - tables
